version: "3.9"

services:
  server:
    env_file:
      - ./backend/.docker.env
    build:
      context: ./backend
    ports:
      - "3000:3000"
  db:
    image: "postgres"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - data:/var/lib/postgresql/data
    command: -p 5433
  react:
    build:
      context: ./client
    ports:
      - "5173:5173"
    stdin_open: true

volumes:
  data:
