version: "3.9"

services:
  server:
    env_file:
      - .docker.env
    build: .
    ports:
      - "3000:3000"
  db:
    image: "postgres"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  data:
